on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: "Login to Docker Hub"
        run: docker login --username shebo280 --password dckr_pat_jgS7wxE0fE9L_hiwcKyJqs-WH2o
